custom hot keys
amrbashir/meilisearch-docsearch pull request #44
Opened 2023-11-13 11:14 UTC by iammapping

Allow set custom hot keys.

The default behaviors are same with previous: Ctrl(⌘)+K or s,/ when not editing, but add abilities to disable the hot keys or set custom ones now

2023-11-13 13:57 UTC, amrbashir requested changes
Thank you for your contributions. Could you also add a change file in `.changes` directory?

2023-11-13 13:57 UTC, amrbashir commented on src/DocSearchButton.tsx
> +      {ctrlWithKey && (
Can we add a fallback here? if `ctrlWithKey` is disabled, we should show one of the singleKeys, probably the first one.

2023-11-14 01:48 UTC, iammapping commented on src/DocSearchButton.tsx
> +      {ctrlWithKey && (
Good idea, this will make the hot keys clearer. Wait a minute, let me modify it

2023-11-14 17:29 UTC, amrbashir approved these changes

2023-11-14 17:29 UTC, amrbashir commented on README.md
> +  }
Let's remove this, I think we should keep the examples as concise and the defaults are good enough for most usecases.

2023-11-14 17:30 UTC, amrbashir commented on README.md
> +  }
```suggestion
```

2023-11-14 19:03 UTC, amrbashir approved these changes
Thank you

2023-11-14 19:04 UTC, merged